// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSXsC7nTUyp4RKh1PvdZDGK_kFR6JQM-w',
    appId: '1:853409652947:web:1dedb771d43369c1f7b426',
    messagingSenderId: '853409652947',
    projectId: 'echeance-fest',
    authDomain: 'echeance-fest.firebaseapp.com',
    storageBucket: 'echeance-fest.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2DzOAsL7wSKH0-_SRYWOzlMn-OAEC6ww',
    appId: '1:853409652947:android:0f8ce8f46a8fe68af7b426',
    messagingSenderId: '853409652947',
    projectId: 'echeance-fest',
    storageBucket: 'echeance-fest.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCSXsC7nTUyp4RKh1PvdZDGK_kFR6JQM-w',
    appId: '1:853409652947:web:078147ea9cef337ef7b426',
    messagingSenderId: '853409652947',
    projectId: 'echeance-fest',
    authDomain: 'echeance-fest.firebaseapp.com',
    storageBucket: 'echeance-fest.firebasestorage.app',
  );

}